baseURL = 'https://kristoferfannar.github.io/'
languageCode = 'en-us'
title = "Kristofer Fannar Bjornsson"

theme="hugo-theme"

[params]
  enableThemeToggle = true

  [params.logo] 
    logoText = " "

  [[params.social]]
    name = "github"
    url = "https://github.com/kristoferfannar"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kristoferfannar"

  [[params.social]]
    name = "email"
    url = "mailto:kristofer.bjornsson@columbia.edu"


[menu]
  [[menu.main]]
    identifier = "cv"
    name       = "cv"
    url        = "https://kristoferfannar.github.io/cv/"
